version: "3.8"

services:
  vless-hub:
    build: .
    container_name: vless-po-gribi-hub
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - ./data:/app/data
      - ./export:/app/export
